FROM shopping-list-base-image:nx-base AS builder

WORKDIR /app/builder
COPY . .
RUN npm i -g http-server
RUN npm i
RUN npx nx build app --prod --verbose

EXPOSE 8080
CMD exec ../../bin/bash -c "trap : TERM INT; sleep infinity & wait"
