name: CI
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: yarn --immutable

      - run: npx nx workspace-lint
      - run: npx nx docker app
      - run: npx nx docker api
